### ISSUE TITLE
Runtime unreachable

### ISSUE THREAD

**Issue by niklasUPB** [Cosmian/CipherCompute#2]
Hey,
I am trying to run CipherCompute. I can log in and follow the Quickstart Guide.
But when I try to simulate a computation I get "Error 500 on http://localhost:9000/computations/23511ba4-599b-45a5-9604-0c3521f4f702/simulate (unable to POST to: http://runtime_0:10000/mpc/simulate/23511ba4-599b-45a5-9604-0c3521f4f702)" and when I try to run a computation I get "Error 500 on http://localhost:9000/computations/23511ba4-599b-45a5-9604-0c3521f4f702/queue (unable to POST to: http://runtime_0:10000/mpc/23511ba4-599b-45a5-9604-0c3521f4f702+9d55cf1b-64d7-460e-8cfa-1f19720e2e49)".
I have tried on kali version 2020.3 and windows 10 I get identical behavior.
When I check the output of CipherCompute it says my demo version is expired but there should be plenty of time left of my 90 days.
  (see out.txt line 109 and below 
[out.txt](https://github.com/Cosmian/CipherCompute/files/8686141/out.txt) )
It also says "unable to GET from: http://runtime_2:10002/mpc/status" (see line 2251 and below) and when I check the status in the UI it also says Runtime unreachable.

![gui](https://user-images.githubusercontent.com/105489239/168262925-4a45c788-c333-4567-9b68-3f6282628957.PNG)

I don't see what I am doing wrong. I have tried to provide all the information I have, please help.

**Comment by ThibsG** [comment]
Hi @niklasUPB ,

Thanks for your interest in CipherCompute.

>  When I check the output of CipherCompute it says my demo version is expired but there should be plenty of time left of my 90 days.

Yes, but it's 90 days starting from compilation day. We were releasing quickly so it wasn't really an issue.

Unfortunately, we are not currently maintaining this product at this time.

If you still want to perform computations, let's try our latest product https://console.cosmian.com

If this product was interesting to you due to its MPC technology, reach us at contact@cosmian.com, 
and we will see if we can help you though
